### ISSUE TITLE
Add github star icon on homepage

### ISSUE THREAD

**Issue by aryanmehrotra** [gofr-dev/website#28]
To create button Refer: https://buttons.github.io/

**Comment by Kapil619** [comment]
Hi,
I can work on this .
Please assign this issue to me .
Meanwhile you can check my portfolio created in Next JS  : https://kapilbadokar.vercel.app/
Best Regards.
Kapil.

**Comment by suhanipaliwal** [comment]
I would like to work on this issue. Please assign me this task.

**Comment by aryanmehrotra** [comment]
<a class="github-button" href="https://github.com/gofr-dev/gofr" data-color-scheme="no-preference: light; light: light; dark: light;" data-size="large" data-show-count="true" aria-label="Star gofr-dev/gofr on GitHub">Star</a>


<script async defer src="https://buttons.github.io/buttons.js"></script>
