### ISSUE TITLE
Bug : Dockerfile size is too large 

### ISSUE THREAD

**Issue by Bhavya-55** [gofr-dev/website#45]
Dockerfile size needs to be reduced. It will reduce build time also helps in overall optimisation

**Comment by Bhavya-55** [comment]
@rokerzfirst101 @aryanmehrotra @naveen-bandela-au2 @gofr-dev I have already worked on this pls assign to me . I can solve the issue. Thanks In advance

**Comment by aryanmehrotra** [comment]
Sure @Bhavya-55
