### ISSUE TITLE
Enhancements and Corrections for README.md Content

### ISSUE THREAD

**Issue by thevijayshankersharma** [gofr-dev/website#47]
The README.md file for our project contains valuable information for users to get started and customize the site. However, there are a few areas where improvements can be made for clarity, consistency, and readability. This issue is raised to implement enhancements and corrections to the README.md content, including grammatical fixes, improved instructions, link formatting, and additional clarity in explanations. The goal is to ensure that users can easily understand and follow the instructions provided in the README.md file.

As a participant of GSSoC (GirlScript Summer of Code), I'm interested in taking on this issue to contribute to the project's improvement. 

Assign this task to me.

**Comment by aryanmehrotra** [comment]
Can you elaborate what all are you proposing to add

**Comment by thevijayshankersharma** [comment]
1. Updating each heading word to start with capital letters

2. Original: To get started with this site, first install the npm dependencies.
    Improved: To begin using this site, start by installing the npm dependencies.

3. Original: You can start editing this template by modifying the files in the /src folder.
    Improved: You can start customizing this template by modifying the files in the /src folder.

4. Original: This feature requires no configuration, and works out of the box by automatically scanning your documentation             
    pages to build its index.
    Improved: The search feature requires no configuration and works out of the box by automatically scanning your     
    documentation pages to build its index.

5. Original: To learn more about the technologies used in this site, see the following resources:
    Improved: To learn more about the technologies used on this site, check out the following resources:
