### ISSUE TITLE
Addition for a Code Playground

### ISSUE THREAD

**Issue by aryanmehrotra** [gofr-dev/website#54]
Dupl : https://github.com/gofr-dev/gofr/issues/605 

@hollermay
I believe it should have a playground to code same we have coding playground at websites to test tools or any programming language and if we add some basic code to execute will also be a good way to create engagement with suggestion codes below the playground or at a sidebar.

**Comment by AyushSingh916** [comment]
Assign this task to me.

**Comment by aryanmehrotra** [comment]
It would be better to use go playground instead of our own playground
