### ISSUE TITLE
Add content in main_test.go

### ISSUE THREAD

**Issue by aryanmehrotra** [gofr-dev/website#82]
Currently, on the homepage main_test.go  is static, allow it to be switchable with correct integration test written for the same.
With both bottom and side scrolling 
<img width="559" alt="Screenshot 2024-08-02 at 2 05 58 AM" src="https://github.com/user-attachments/assets/b871873e-3e7b-425d-9aa7-091a7919e3ac">

**Comment by Rakshita-ZS** [comment]
I am picking this issue 
This is the PR link -> https://github.com/gofr-dev/website/pull/86
