### ISSUE TITLE
Fix go to top when clicked on features tabs

### ISSUE THREAD

**Issue by aryanmehrotra** [gofr-dev/website#83]
These tabs are only to make it visually appealing, but when clicked on these it takes to the top of the screen.

<img width="1393" alt="Screenshot 2024-08-02 at 2 04 24 AM" src="https://github.com/user-attachments/assets/51014078-7aae-484e-8e3a-9443c78c3487">

**Comment by leidorf** [comment]
hi, i can work on this. can you assign it to me?

**Comment by aryanmehrotra** [comment]
@leidorf PR has already been created by multiple developers, will be going ahead with the first one.

You can watch the repo for future issues.
